# VIM keys
set-window-option -g mode-keys vi

# Move directly to copy mode
bind -n C-s copy-mode

# use P to paste tmux clibboard
bind P paste-buffer

# Bind n/p to scroll to prompts
bind -T copy-mode-vi n send-keys -X search-forward "▶"
bind -T copy-mode-vi p send-keys -X search-backward "▶"

# Switch prefix to ctrl+j
# un-done because I prefer ctrl+j to move panes
# set -g prefix C-p
# unbind C-b
# bind C-p send-prefix

# New split command bindings
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

# Reload config
bind r source-file ~/.tumx.conf

# Kill current session
bind X confirm-before kill-session

# Select like VIM
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
# New window movement bindings
#bind -n C-h select-pane -L
#bind -n C-l select-pane -R
#bind -n C-k select-pane -U
#bind -n C-j select-pane -D
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'" 
bind -n C-k run-shell "if $is_vim ; then tmux send-keys C-k; else tmux select-pane -U; fi"
bind -n C-j run-shell "if $is_vim ; then tmux send-keys C-j; else tmux select-pane -D; fi"
bind -n C-h run-shell "if $is_vim ; then tmux send-keys C-h; else tmux select-pane -L; fi"
bind -n C-l run-shell "if $is_vim ; then tmux send-keys C-l; else tmux select-pane -R; fi"
# Custom binding to switch to local_graphene tmux session
#bind -n C-g switch-client -t "local_graphene"

# Status bar colors
set -g status-bg colour57
set -g status-fg colour255
set -g status-right "#[fg=colour57]"

# Set window number index
set -g base-index 1

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Experiments
set -g mouse on
setw -g monitor-activity on
set -g visual-activity on
