#! /bin/bash

sqlite3 ~/Library/Messages/chat.db 'select count(*) from message where is_from_me == 0 and is_read == 0 and text not null and datetime(date/1000000000 + strftime("%s", "2001-01-01"), "unixepoch", "localtime") > datetime("now", "start of day");'
