#!/bin/bash

source "$HOME/.zshfn/.git-prompt.sh"

red='\001\033[1;31m\002'
red_length=${#red}
yellow='\001\033[1;33m\002'
yellow_length=${#yellow}
green='\001\033[1;32m\002'
green_length=${#green}
turquoise='\001\033[1;36m\002'
turquoise_length=${#turquoise}
purple='\001\033[1;34m\002'
nocolor='\001\033[0m\002'
nocolor_length=${#nocolor}
curve_up_right='\xe2\x95\xad'
curve_up_left='\xe2\x95\xae'
curve_down_right='\xe2\x95\xb0'
curve_down_left='\xe2\x95\xaf'
horizontal_line='\xe2\x94\x80'
tee_right='\xe2\x94\x9c'
tee_left='\xe2\x94\xa4'
flag_icon='\xe2\x9a\x91'
snake='\xf0\x9f\x90\x8d'
eso='\001'
esc='\002'

current_working_dir=$(pwd)
git_string=$(__git_ps1)
# unread_texts_string=$(count_unread_texts.sh)
unread_texts_string="test"
if [ -n "$VIRTUAL_ENV" ]
 then
  virtualenv_segment=$(echo $VIRTUAL_ENV | rev | cut -d '/' -f1 | rev)
  virtualenv_string=" $snake $virtualenv_segment "
  virtualenv_string_length=${#virtualenv_segment}+5
 else
  virtualenv_string=""
  virtualenv_string_length=${#virtualenv_string}
fi
weather_string_length=${#weather_string}
current_working_dir_length=${#current_working_dir}
git_string_length=${#git_string}
unread_texts_string_length=${#unread_texts_string}
prompt_line_one="\001$red\002$curve_up_right$horizontal_line \001$turquoise\002$current_working_dir \001$red\002$horizontal_line$horizontal_line$horizontal_line \001$yellow\002$flag_icon $unread_texts_string $flag_icon \001$red\002$horizontal_line$curve_up_left\001$nocolor\002"
line_one_length=$(($current_working_dir_length+$unread_texts_string_length+15))


fill_line()
{
  if [ "$git_string_length" -gt "0" ]
  then
    printf " ";
    local counter=$(($git_string_length+5+$virtualenv_string_length));
    while ((counter++ < $line_one_length)); do
      printf $horizontal_line;
    done
  else
    local counter=$(($git_string_length+4+$virtualenv_string_length));
    while ((counter++ < $line_one_length)); do
      printf $horizontal_line;
    done
  fi
}

# prompt_line_two="\001$red\002$tee_right$horizontal_line\001$green\002$git_string\001$red\002$(fill_line)\001$purple\002$virtualenv_string\001$red\002$horizontal_line$curve_down_left"
prompt_line_two="\001$red\002$curve_down_right$horizontal_line\001$green\002$git_string\001$red\002$(fill_line)\001$purple\002$virtualenv_string\001$red\002$horizontal_line$curve_down_left\001$nocolor\002"

if [[ -n $TERMINAL_EMULATOR ]]
then
  echo -e "\n$current_working_dir |$git_string"
  echo -e "> "
else
  printf "\n$prompt_line_one"
  printf "\n$prompt_line_two\n"
  echo -n "%F{red}▶ %f"
fi
