# start ZSH profiler
#zmodload zsh/zprof

# homebrew setup
eval "$(/opt/homebrew/bin/brew shellenv)"

# add other executables to path
path=(
  "/opt/homebrew/opt/llvm/bin"
  "/opt/homebrew/opt/mysql@8.0/bin"
  "$HOME/bin"
  "$HOME/Library/Application Support/Coursier/bin/"
  "$HOME/.dotfiles/path_scripts"
  "$HOME/.local/bin"
  "$HOME/.cargo/bin"
  "/opt/madlib"
  "${path[@]}")

# add custom functions from fpath
fpath=(
  "$HOME/.zshfn"
  "/opt/homebrew/share/zsh/site-functions"
  "$HOME/Library/Application Support/ScalaCli/completions/zsh"
  "$HOME/.cache/mill/download/mill-completion.sh"
  "${fpath[@]}")
autoload -Uz $fpath[1]/*(.:t)

# The following lines were added by compinstall

zstyle ':completion:*' auto-description 'specify: %d'
#
zstyle ':completion:*:descriptions' format '%F{blue}╾┤ %d ├╼%f'
zstyle ':completion:*' group-name ''
#
zstyle ':completion:*' completer _complete _ignored _correct
zstyle ':completion:*' completions 0
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 10
zstyle ':completion:*' menu select=1
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path $HOME/.zcompcache
zstyle :compinstall filename '/Users/brian.tracey/.zshrc'
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char

autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit
# End of lines added by compinstall

# customize zsh for mise
update_mise_gh_token() {
  export MISE_GITHUB_TOKEN="$(gh auth token)"
}
declare -a precmd_functions
precmd_functions+=(update_mise_gh_token)

# add aws completion at each login
complete -C $(which aws_completer) aws

# wezterm shell integration
test -e $HOME/.wezterm.sh && source $HOME/.wezterm.sh

#mise-en-place setup
eval "$(mise activate zsh)"

# fzf setup
source <(fzf --zsh)

# work tokens
test -e "$HOME"/.work_tokens && source "$HOME"/.work_tokens
# vault setup
eval "$(vutil set-env zsh)"

# starship prompt
eval "$(starship init zsh)"

# orbstack setup
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

source "$HOME"/.zsh_opts
source "$HOME"/.zsh_input_opts
source "$HOME"/.zsh_aliases
source "$HOME"/.zsh_env
source "$HOME"/.zsh/plugins/mill-zsh-completions/mill-zsh-completions.plugin.zsh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/vault vault

# end ZSH profiler
#zprof
