# start ZSH profiler
#zmodload zsh/zprof

# homebrew setup
eval "$(/opt/homebrew/bin/brew shellenv)"

# wttr command options
export WTTR_PARAMS="0 q m"

# Argos server LOCAL
export ENV=LOCAL

# add other executables to path
path=( "/opt/homebrew/opt/llvm/bin"
       "/opt/homebrew/opt/mysql@8.0/bin"
       "$HOME/bin"
       "$HOME/Library/Application Support/Coursier/bin"
       "$HOME/.dotfiles/path_scripts"
       "$HOME/.local/bin"
       "$HOME/.lmstudio/bin"
       "${path[@]}" )

# add custom functions from fpath
fpath=( "$HOME/.zshfn"
        "/opt/homebrew/share/zsh/site-functions"
        "$HOME/Library/Application Support/ScalaCli/completions/zsh"
        "$HOME/.zsh/plugins/mill-zsh-completions/completions/"
        "${fpath[@]}" )
autoload -Uz $HOME/.zshfn/*(.:t)

## load zsh colors
autoload -U colors && colors
## execute spectrum command to support color escape code shortcuts
spectrum

# The following lines were added by compinstall

zstyle ':completion:*' auto-description 'specify: %d'
#
zstyle ':completion:*:descriptions' format '%F{blue}╾┤ %d ├╼%f'
zstyle ':completion:*' group-name ''
#
zstyle ':completion:*' completer _complete _ignored _correct
zstyle ':completion:*' completions 0
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 10
zstyle ':completion:*' menu select=1
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path $HOME/.zcompcache
zstyle :compinstall filename '/Users/brian.tracey/.zshrc'
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char

autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit
# End of lines added by compinstall

# zsh precmd functions
typeset -a precmd_functions
precmd_functions+=(update_mise_gh_token)

# wezterm shell integration
test -e $HOME/.wezterm.sh && source $HOME/.wezterm.sh

#mise-en-place setup
eval "$(mise activate zsh)"

# fzf setup
source <(fzf --zsh)

# work tokens
test -e $HOME/.work_tokens && source $HOME/.work_tokens

# starship prompt
eval "$(starship init zsh)"

# ZSH options
source $HOME/.zsh_opts
# ZSH input options
source $HOME/.zsh_input_opts
# aliases
source $HOME/.aliases
# ZSH plugins
# source "$HOME/.zsh/plugins/mill-zsh-completions/mill-zsh-completions.plugin.zsh"

export LDFLAGS="-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib/unwind -lunwind"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
# end ZSH profiler
#zprof

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/brian.tracey/.lmstudio/bin"
# End of LM Studio CLI section

