[settings]
    env_file            = ".env"
    experimental        = true
    python.uv_venv_auto = "create|source"
[tools]
    go        = "1.25.3"
    node      = "22"
    "pipx:ty" = "latest"
    python    = "3.14.3"
    ruff      = "latest"
    uv        = "latest"
    java      = "temurin-21"
    # ruby      = "3.2.0"
    ruby = "latest"
bun = "latest"
